workflows:
  native-android:
    name: Native Android
    max_build_duration: 30
    instance_type: mac_mini_m1
    environment:
      vars:
        PACKAGE_NAME: "com.palfs.mvcapplication"
    scripts:
      - name: Build Android APK
        working_directory: android
        script: ./gradlew assembleDebug
    artifacts:
      - app/build/outputs/**/**/*.apk
    publishing:
      email:
        recipients:
          - pyrata786@gmail.com
        notify:
          success: true
          failure: true
