workflows:
  android-workflow:
    name: Native Android
    max_build_duration: 30
    environment:
      vars:
        PACKAGE_NAME: "com.palfs.mvcapplication"
    scripts:
      - name: Set Android SDK location
        script: |
          echo "sdk.dir=$ANDROID_SDK_ROOT" > "$CM_BUILD_DIR/local.properties"
      - name: Build Android APK
        working_directory: android
        script: ./gradlew assembleDebug
    artifacts:
      - app/build/outputs/**/**/*.apk
    publishing:
      email:
        recipients:
          - pyrata786@gmail.com
        notify:
          success: true
          failure: true
